version: '3.8'
services:
  web-server:
    build: ./lilee_fastapi
    ports:
      - "9000:9000"
    depends_on:
      - mysqlDB
    environment:
      - DATABASE_URL=mysql+pymysql://root:1qaz2wsx@mysqlDB:3306/lilee
  mysqlDB:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz2wsx
      MYSQL_DATABASE: lilee
    ports:
      - "3308:3306"
  vue-app:
    build: ./lilee_vue
    ports:
      - "8080:8080"
