"""Add new columns to users and groups table

Revision ID: 16bf9942d657
Revises: 069f07af7ba6
Create Date: 2024-04-05 22:21:26.317119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bf9942d657'
down_revision: Union[str, None] = '069f07af7ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('is_activate', sa.Boolean(), nullable=True))
    op.add_column('groups', sa.Column('creator', sa.String(length=255), nullable=True))
    op.add_column('groups', sa.Column('createdTime', sa.DateTime(), nullable=True))
    op.add_column('groups', sa.Column('modifier', sa.String(length=255), nullable=True))
    op.add_column('groups', sa.Column('modifiedTime', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_activate', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('creator', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('createdTime', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('modifier', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('modifiedTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_activate')
    op.drop_column('users', 'modifiedTime')
    op.drop_column('users', 'modifier')
    op.drop_column('users', 'createdTime')
    op.drop_column('users', 'creator')
    op.drop_column('groups', 'is_activate')
    op.drop_column('groups', 'modifiedTime')
    op.drop_column('groups', 'modifier')
    op.drop_column('groups', 'createdTime')
    op.drop_column('groups', 'creator')
    # ### end Alembic commands ###
